use anchor_lang::prelude::*;
use anchor_lang::solana_program::{program::invoke, program::invoke_signed, system_instruction};
use anchor_lang::solana_program::alt_bn128::prelude::*;
use anchor_spl::associated_token::AssociatedToken;
use anchor_spl::token_2022::{spl_token_2022, Token2022};

declare_id!("DwiHe1VWW9KXeWXJFaRFoMNzPt3mVs2Ac84gPbaeBkoJ");

/// Attestation validity period: 30 days in seconds.
pub const ATTESTATION_DURATION: i64 = 30 * 24 * 3600;

/// Byte length of a Token-2022 Mint with NonTransferable extension.
///
/// Layout: PodMint(82) + Padding(83) + AccountType(1) + TLV header(4) = 170
pub const SOULBOUND_MINT_LEN: usize = 170;

// ---------------------------------------------------------------------------
// Groth16 Verification Key
// ---------------------------------------------------------------------------
// Generated by running the trusted setup:
//   cd circuits/income_proof_circom
//   npm install
//   wget https://hermez.s3-eu-west-1.amazonaws.com/powersOfTau28_hez_final_12.ptau -O pot12_final.ptau
//   npm run setup
// Then copy the printed constants here (node extract_vk.js).
//
// All coordinates are BN254 base-field elements encoded as big-endian 32-byte arrays.
// G1 = 64 bytes (x[32] || y[32])
// G2 = 128 bytes (x_im[32] || x_re[32] || y_im[32] || y_re[32])

const VK_ALPHA_G1: [u8; 64] = [
    0x0a, 0xda, 0x6e, 0x07, 0xca, 0x85, 0xb1, 0x81,
    0xee, 0x55, 0xc7, 0xf2, 0x9c, 0x76, 0x0a, 0x8b,
    0x72, 0x2b, 0x66, 0xba, 0xd2, 0x23, 0x2d, 0x97,
    0x9c, 0xb6, 0xe0, 0x27, 0x67, 0xcd, 0x04, 0xb8,
    0x1d, 0x08, 0xf8, 0xda, 0x77, 0x4a, 0xe0, 0x18,
    0xe2, 0x62, 0x82, 0x96, 0x39, 0xc4, 0x46, 0xe3,
    0xbf, 0x2f, 0xe2, 0x09, 0xff, 0x0b, 0x35, 0x69,
    0x64, 0xfa, 0xcc, 0x70, 0x35, 0x0a, 0x0d, 0x40,
];
const VK_BETA_G2: [u8; 128] = [
    0x24, 0x0b, 0xef, 0xb7, 0x83, 0x5e, 0x17, 0xfc,
    0x1e, 0xdf, 0x87, 0xfb, 0xd3, 0x18, 0x1b, 0xee,
    0x8a, 0xad, 0x28, 0xf8, 0x3e, 0x52, 0x76, 0x60,
    0x0c, 0x64, 0x45, 0x69, 0x25, 0x8c, 0x51, 0xd4,
    0x2c, 0x39, 0x7e, 0x34, 0x57, 0xde, 0x25, 0xb2,
    0x65, 0x4f, 0x9a, 0x9b, 0x38, 0x70, 0xe1, 0xe3,
    0x6f, 0x81, 0xf1, 0x0b, 0x3d, 0x27, 0xa5, 0x43,
    0xd9, 0x24, 0x06, 0xde, 0xa1, 0x54, 0x9d, 0x5d,
    0x25, 0xd6, 0x1e, 0x04, 0x42, 0x5e, 0x1a, 0xc1,
    0xd0, 0xa3, 0xbb, 0x37, 0x55, 0xf5, 0x12, 0xa2,
    0xcf, 0x40, 0x02, 0xdf, 0xd6, 0x37, 0x32, 0xed,
    0xbe, 0x27, 0x4b, 0x28, 0x1c, 0x21, 0x23, 0xe8,
    0x04, 0xd7, 0xf3, 0x12, 0xda, 0xe5, 0xb5, 0x4c,
    0x0b, 0x76, 0x67, 0x8a, 0xbe, 0xdb, 0xc1, 0x4a,
    0x6e, 0xcb, 0x19, 0x48, 0x43, 0x83, 0x68, 0x4d,
    0xae, 0xef, 0xc5, 0x3b, 0x9f, 0xfd, 0x65, 0xb6,
];
const VK_GAMMA_G2: [u8; 128] = [
    0x19, 0x8e, 0x93, 0x93, 0x92, 0x0d, 0x48, 0x3a,
    0x72, 0x60, 0xbf, 0xb7, 0x31, 0xfb, 0x5d, 0x25,
    0xf1, 0xaa, 0x49, 0x33, 0x35, 0xa9, 0xe7, 0x12,
    0x97, 0xe4, 0x85, 0xb7, 0xae, 0xf3, 0x12, 0xc2,
    0x18, 0x00, 0xde, 0xef, 0x12, 0x1f, 0x1e, 0x76,
    0x42, 0x6a, 0x00, 0x66, 0x5e, 0x5c, 0x44, 0x79,
    0x67, 0x43, 0x22, 0xd4, 0xf7, 0x5e, 0xda, 0xdd,
    0x46, 0xde, 0xbd, 0x5c, 0xd9, 0x92, 0xf6, 0xed,
    0x09, 0x06, 0x89, 0xd0, 0x58, 0x5f, 0xf0, 0x75,
    0xec, 0x9e, 0x99, 0xad, 0x69, 0x0c, 0x33, 0x95,
    0xbc, 0x4b, 0x31, 0x33, 0x70, 0xb3, 0x8e, 0xf3,
    0x55, 0xac, 0xda, 0xdc, 0xd1, 0x22, 0x97, 0x5b,
    0x12, 0xc8, 0x5e, 0xa5, 0xdb, 0x8c, 0x6d, 0xeb,
    0x4a, 0xab, 0x71, 0x80, 0x8d, 0xcb, 0x40, 0x8f,
    0xe3, 0xd1, 0xe7, 0x69, 0x0c, 0x43, 0xd3, 0x7b,
    0x4c, 0xe6, 0xcc, 0x01, 0x66, 0xfa, 0x7d, 0xaa,
];
const VK_DELTA_G2: [u8; 128] = [
    0x10, 0x93, 0x3c, 0x5f, 0xb6, 0x9a, 0xed, 0xf9,
    0x6f, 0x2d, 0xda, 0x55, 0x85, 0x9f, 0x2b, 0x54,
    0x25, 0xda, 0x9e, 0xf4, 0x7a, 0x07, 0x96, 0x2b,
    0xba, 0xa9, 0xf5, 0xf4, 0xd5, 0x1e, 0x6b, 0x73,
    0x29, 0xf7, 0xfc, 0xaf, 0x7c, 0x6e, 0x10, 0x48,
    0x33, 0xe1, 0xcf, 0xcb, 0xf1, 0x5c, 0x31, 0x21,
    0x7b, 0x9a, 0x6f, 0x5a, 0xf2, 0x06, 0xa8, 0xa6,
    0xe0, 0x2c, 0xf6, 0xd5, 0xe2, 0x2a, 0x9c, 0x38,
    0x0f, 0x24, 0xe6, 0xe5, 0x80, 0x6a, 0x4a, 0x70,
    0x9f, 0x8e, 0xad, 0x58, 0xc6, 0x1f, 0x69, 0xdf,
    0xcc, 0xbd, 0xaf, 0x5d, 0x60, 0xd8, 0x3d, 0xf9,
    0x72, 0x56, 0xac, 0xd9, 0x61, 0x60, 0xae, 0x56,
    0x1e, 0xe0, 0x5a, 0x0e, 0xd0, 0xe2, 0x9c, 0x20,
    0x0f, 0x58, 0x2f, 0xcb, 0x2c, 0xc5, 0x15, 0xfd,
    0x83, 0x4b, 0x77, 0x66, 0x1f, 0x17, 0x97, 0x3e,
    0x1d, 0x9c, 0x53, 0x23, 0x75, 0xc4, 0xc8, 0x77,
];
const VK_IC0: [u8; 64] = [
    0x21, 0x4a, 0x4a, 0x4e, 0xdc, 0x81, 0x8c, 0x65,
    0x92, 0xc1, 0x42, 0xeb, 0xbe, 0xe2, 0x05, 0xb0,
    0x24, 0x1e, 0x98, 0x11, 0xc1, 0x55, 0xa9, 0x06,
    0xf1, 0xcf, 0xfa, 0xab, 0x02, 0xb4, 0xa2, 0x59,
    0x21, 0x53, 0x2c, 0xad, 0xdc, 0x83, 0x16, 0xe0,
    0x5b, 0xee, 0x2b, 0x59, 0x63, 0x95, 0x9c, 0x8b,
    0x98, 0x0f, 0x15, 0xfc, 0x4b, 0xf8, 0x1a, 0x78,
    0x43, 0xc2, 0x5c, 0x2a, 0xc2, 0x63, 0xdc, 0xb9,
];
const VK_IC1: [u8; 64] = [
    0x03, 0x4b, 0xe8, 0xe8, 0x39, 0x0d, 0x7c, 0xc3,
    0x20, 0xe3, 0xac, 0x43, 0x49, 0xf2, 0xc8, 0x30,
    0x56, 0x31, 0x7c, 0xb8, 0xb7, 0xbd, 0x6a, 0x97,
    0x95, 0x55, 0x42, 0xf0, 0xd7, 0x70, 0x78, 0x04,
    0x2f, 0xde, 0x64, 0xdf, 0xc5, 0xb2, 0x1f, 0x8f,
    0xec, 0x12, 0xb4, 0x8d, 0x03, 0xdf, 0xde, 0xc1,
    0x47, 0x0f, 0xbe, 0x13, 0x0c, 0x3a, 0x4f, 0x3d,
    0xbf, 0xaf, 0x1e, 0x54, 0xfc, 0xa3, 0x59, 0xd3,
];

/// BN254 base-field prime q (big-endian), used for G1 point negation.
const BN254_Q: [u8; 32] = [
    0x30, 0x64, 0x4e, 0x72, 0xe1, 0x31, 0xa0, 0x29,
    0xb8, 0x50, 0x45, 0xb6, 0x81, 0x81, 0x58, 0x5d,
    0x97, 0x81, 0x6a, 0x91, 0x68, 0x71, 0xca, 0x8d,
    0x3c, 0x20, 0x8c, 0x16, 0xd8, 0x7c, 0xfd, 0x47,
];

/// Negates a G1 affine point: (x, y) → (x, q − y), big-endian 32-byte coordinates.
fn negate_g1(point: &[u8]) -> [u8; 64] {
    let mut out = [0u8; 64];
    out[..32].copy_from_slice(&point[..32]); // x is unchanged
    let y = &point[32..64];
    let mut borrow: i16 = 0;
    for i in (0..32).rev() {
        let sub = BN254_Q[i] as i16 - y[i] as i16 - borrow;
        out[32 + i] = sub.rem_euclid(256) as u8;
        borrow = if sub < 0 { 1 } else { 0 };
    }
    out
}

// ---------------------------------------------------------------------------
// On-chain Groth16 verification helper
// ---------------------------------------------------------------------------

/// Verifies a Circom/snarkjs BN254 Groth16 proof using Solana's native
/// alt_bn128 precompile syscalls (~100 K CU: mul 3.5K + add 334 + pairing 72.7K + overhead).
///
/// proof layout (256 bytes):
///   [  0.. 64)  pi_a — G1 (x: 32 B, y: 32 B, big-endian)
///   [ 64..192)  pi_b — G2 (x_im: 32, x_re: 32, y_im: 32, y_re: 32, big-endian)
///   [192..256)  pi_c — G1 (x: 32 B, y: 32 B, big-endian)
///
/// public_values: [tier: u8]  where tier ∈ {1, 2}
///
/// Pairing equation checked:
///   e(A, B) · e(−α, β) · e(−vk_x, γ) · e(−C, δ) == 1
/// where vk_x = IC[0] + tier · IC[1]
///
/// Compiled with --features verify-skip the check is omitted for local tests.
/// NEVER deploy with verify-skip.
fn verify_groth16_proof(proof: &[u8], public_values: &[u8]) -> Result<()> {
    require!(proof.len() == 256, SeelError::InvalidProof);
    require!(!public_values.is_empty(), SeelError::InvalidProof);

    let tier = public_values[0] as u64;

    let pi_a = &proof[0..64];
    let pi_b = &proof[64..192];
    let pi_c = &proof[192..256];

    // ── vk_x = IC[0] + tier * IC[1] ──────────────────────────────────────

    let mut tier_scalar = [0u8; 32];
    tier_scalar[24..].copy_from_slice(&tier.to_be_bytes());

    let mut mul_in = [0u8; 96];
    mul_in[..64].copy_from_slice(&VK_IC1);
    mul_in[64..].copy_from_slice(&tier_scalar);

    let tier_ic = alt_bn128_multiplication(&mul_in)
        .map_err(|_| error!(SeelError::InvalidProof))?;

    let mut add_in = [0u8; 128];
    add_in[..64].copy_from_slice(&VK_IC0);
    add_in[64..].copy_from_slice(&tier_ic);
    let vk_x = alt_bn128_addition(&add_in)
        .map_err(|_| error!(SeelError::InvalidProof))?;

    // ── Negate the three G1 points that appear on the RHS ────────────────
    let neg_alpha = negate_g1(&VK_ALPHA_G1);
    let neg_vk_x  = negate_g1(&vk_x);
    let neg_pi_c  = negate_g1(pi_c);

    // ── Build 4-pair input for alt_bn128_pairing (768 bytes) ─────────────
    //   e(A, B) · e(−α, β) · e(−vk_x, γ) · e(−C, δ) == 1
    let mut pairs = [0u8; 768];

    pairs[  0.. 64].copy_from_slice(pi_a);
    pairs[ 64..192].copy_from_slice(pi_b);

    pairs[192..256].copy_from_slice(&neg_alpha);
    pairs[256..384].copy_from_slice(&VK_BETA_G2);

    pairs[384..448].copy_from_slice(&neg_vk_x);
    pairs[448..576].copy_from_slice(&VK_GAMMA_G2);

    pairs[576..640].copy_from_slice(&neg_pi_c);
    pairs[640..768].copy_from_slice(&VK_DELTA_G2);

    let result = alt_bn128_pairing(&pairs)
        .map_err(|_| error!(SeelError::InvalidProof))?;

    let mut expected = [0u8; 32];
    expected[31] = 1;
    require!(result == expected, SeelError::InvalidProof);

    Ok(())
}

#[program]
pub mod seel {
    use super::*;

    /// Verifies a Circom Groth16 income proof on-chain and mints (or renews) an
    /// attestation soulbound token for `user`.
    ///
    /// 1. On-chain BN254 Groth16 proof verification (~400–600 K CU via precompile).
    /// 2. Creates (or renews) the AttestationAccount PDA for `user`.
    /// 3. On first call: initialises a Token-2022 NonTransferable mint PDA and
    ///    mints one soulbound badge token to the user's associated token account.
    pub fn mint_attestation(
        ctx: Context<MintAttestation>,
        proof: Vec<u8>,          // Groth16 proof bytes (256 bytes: pi_a || pi_b || pi_c)
        public_values: Vec<u8>,  // public signals: [tier: u8]
    ) -> Result<()> {
        // ── 0. On-chain ZK verification ────────────────────────────────────────
        verify_groth16_proof(&proof, &public_values)?;

        require!(!public_values.is_empty(), SeelError::InvalidPublicValues);
        let tier = public_values[0];
        require!(tier == 1 || tier == 2, SeelError::InvalidTier);

        let proof_hash: [u8; 32] = {
            use anchor_lang::solana_program::hash::hash;
            hash(&proof).to_bytes()
        };

        // ── 1. Update attestation PDA ──────────────────────────────────────────
        let clock = Clock::get()?;
        let att = &mut ctx.accounts.attestation;
        att.owner = ctx.accounts.user.key();
        att.issuer = ctx.accounts.authority.key();
        att.tier = tier;
        att.issued_at = clock.unix_timestamp;
        att.expires_at = clock.unix_timestamp + ATTESTATION_DURATION;
        att.proof_hash = proof_hash;
        att.bump = ctx.bumps.attestation;

        // ── 2. Token-2022 soulbound mint (first call only) ────────────────────
        let user_key = ctx.accounts.user.key();
        let mint_bump = ctx.bumps.soulbound_mint;
        let pda_seeds: &[&[u8]] = &[b"soulbound_mint", user_key.as_ref(), &[mint_bump]];

        let mint_info          = ctx.accounts.soulbound_mint.to_account_info();
        let token_account_info = ctx.accounts.soulbound_token_account.to_account_info();
        let authority_info     = ctx.accounts.authority.to_account_info();
        let system_program_info = ctx.accounts.system_program.to_account_info();
        let t22_program_info   = ctx.accounts.token_2022_program.to_account_info();

        if mint_info.lamports() == 0 {
            let rent = Rent::get()?;
            let lamports = rent.minimum_balance(SOULBOUND_MINT_LEN);

            invoke_signed(
                &system_instruction::create_account(
                    authority_info.key,
                    mint_info.key,
                    lamports,
                    SOULBOUND_MINT_LEN as u64,
                    ctx.accounts.token_2022_program.key,
                ),
                &[authority_info.clone(), mint_info.clone(), system_program_info.clone()],
                &[pda_seeds],
            )?;

            invoke(
                &spl_token_2022::instruction::initialize_non_transferable_mint(
                    ctx.accounts.token_2022_program.key,
                    mint_info.key,
                )?,
                &[mint_info.clone(), t22_program_info.clone()],
            )?;

            invoke(
                &spl_token_2022::instruction::initialize_mint2(
                    ctx.accounts.token_2022_program.key,
                    mint_info.key,
                    authority_info.key,
                    None,
                    0,
                )?,
                &[mint_info.clone(), t22_program_info.clone()],
            )?;
        }

        if token_account_info.lamports() == 0 {
            anchor_spl::associated_token::create(CpiContext::new(
                ctx.accounts.associated_token_program.to_account_info(),
                anchor_spl::associated_token::Create {
                    payer:            authority_info.clone(),
                    associated_token: token_account_info.clone(),
                    authority:        ctx.accounts.user.to_account_info(),
                    mint:             mint_info.clone(),
                    system_program:   system_program_info.clone(),
                    token_program:    t22_program_info.clone(),
                },
            ))?;

            invoke(
                &spl_token_2022::instruction::mint_to(
                    ctx.accounts.token_2022_program.key,
                    mint_info.key,
                    token_account_info.key,
                    authority_info.key,
                    &[],
                    1,
                )?,
                &[mint_info.clone(), token_account_info.clone(), authority_info.clone()],
            )?;

            msg!("Soulbound token minted to {}", ctx.accounts.user.key());
        }

        emit!(AttestationMinted {
            owner: att.owner,
            tier,
            expires_at: att.expires_at,
        });
        msg!(
            "Attestation minted: owner={} tier={} expires={}",
            att.owner,
            tier,
            att.expires_at
        );
        Ok(())
    }

    /// Closes an expired attestation account.
    ///
    /// Anyone may call this once the account has passed its `expires_at`.
    /// Lamports are returned to the original user.
    pub fn expire_attestation(ctx: Context<ExpireAttestation>) -> Result<()> {
        let clock = Clock::get()?;
        require!(
            ctx.accounts.attestation.expires_at < clock.unix_timestamp,
            SeelError::NotExpired
        );
        msg!("Attestation expired: owner={}", ctx.accounts.attestation.owner);
        Ok(())
    }

    /// Forcibly revokes an attestation before its expiry.
    ///
    /// Only the original issuer (authority) may call this.
    pub fn revoke_attestation(ctx: Context<RevokeAttestation>) -> Result<()> {
        require!(
            ctx.accounts.authority.key() == ctx.accounts.attestation.issuer,
            SeelError::Unauthorized
        );
        msg!("Attestation revoked: owner={}", ctx.accounts.attestation.owner);
        Ok(())
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Account contexts
// ─────────────────────────────────────────────────────────────────────────────

#[derive(Accounts)]
pub struct MintAttestation<'info> {
    #[account(
        init_if_needed,
        payer = authority,
        space = AttestationAccount::LEN,
        seeds = [b"attestation", user.key().as_ref()],
        bump,
    )]
    pub attestation: Account<'info, AttestationAccount>,

    /// CHECK: pubkey used as PDA seed and as the ATA authority; no data read.
    pub user: UncheckedAccount<'info>,

    #[account(mut)]
    pub authority: Signer<'info>,

    /// CHECK: manually initialised with NonTransferable extension in mint_attestation.
    #[account(
        mut,
        seeds = [b"soulbound_mint", user.key().as_ref()],
        bump,
    )]
    pub soulbound_mint: UncheckedAccount<'info>,

    /// CHECK: caller must pass the ATA of (user, soulbound_mint, Token-2022).
    #[account(mut)]
    pub soulbound_token_account: UncheckedAccount<'info>,

    pub system_program: Program<'info, System>,
    pub token_2022_program: Program<'info, Token2022>,
    pub associated_token_program: Program<'info, AssociatedToken>,
}

#[derive(Accounts)]
pub struct ExpireAttestation<'info> {
    #[account(
        mut,
        close = user,
        seeds = [b"attestation", user.key().as_ref()],
        bump = attestation.bump,
        constraint = attestation.owner == user.key() @ SeelError::InvalidOwner,
    )]
    pub attestation: Account<'info, AttestationAccount>,

    /// CHECK: receives the reclaimed lamports.
    #[account(mut)]
    pub user: UncheckedAccount<'info>,
}

#[derive(Accounts)]
pub struct RevokeAttestation<'info> {
    #[account(
        mut,
        close = user,
        seeds = [b"attestation", user.key().as_ref()],
        bump = attestation.bump,
        constraint = attestation.owner == user.key() @ SeelError::InvalidOwner,
    )]
    pub attestation: Account<'info, AttestationAccount>,

    /// CHECK: receives the reclaimed lamports.
    #[account(mut)]
    pub user: UncheckedAccount<'info>,

    pub authority: Signer<'info>,
}

// ─────────────────────────────────────────────────────────────────────────────
// State
// ─────────────────────────────────────────────────────────────────────────────

#[account]
pub struct AttestationAccount {
    pub owner:      Pubkey,    // 32
    pub issuer:     Pubkey,    // 32
    pub tier:       u8,        // 1
    pub issued_at:  i64,       // 8
    pub expires_at: i64,       // 8
    pub proof_hash: [u8; 32],  // 32  SHA-256 of raw proof bytes
    pub bump:       u8,        // 1
}

impl AttestationAccount {
    pub const LEN: usize = 8 + 32 + 32 + 1 + 8 + 8 + 32 + 1; // = 122
}

// ─────────────────────────────────────────────────────────────────────────────
// Events
// ─────────────────────────────────────────────────────────────────────────────

#[event]
pub struct AttestationMinted {
    pub owner:      Pubkey,
    pub tier:       u8,
    pub expires_at: i64,
}

// ─────────────────────────────────────────────────────────────────────────────
// Errors
// ─────────────────────────────────────────────────────────────────────────────

#[error_code]
pub enum SeelError {
    #[msg("Groth16 proof verification failed")]
    InvalidProof,

    #[msg("Public values must be non-empty")]
    InvalidPublicValues,

    #[msg("Tier must be 1 (≥$2k/mo) or 2 (≥$5k/mo)")]
    InvalidTier,

    #[msg("Attestation has not expired yet")]
    NotExpired,

    #[msg("Account owner mismatch")]
    InvalidOwner,

    #[msg("Only the original issuer may revoke this attestation")]
    Unauthorized,
}
